import {
  Globe,
  TrendingUp,
  ExternalLink,
  Star,
  Users,
  ArrowRight,
  Zap,
  ShieldCheck,
  ClipboardList,
  Leaf,
  Camera,
  Stethoscope,
  Store,
  Smile,
} from 'lucide-react';
import { ProjectType } from './types';
export const caseStudies: ProjectType[] = [
  {
    id: 17,
    title: 'Stock Mate AI',
    subtitle: 'AI for Behavioral Health & Compliance Screening',
    description:
      'Streamlined AI solution for behavioral health assessments, compliance evaluations, and recovery support workflows.',
    longDescription:
      'Acetdui empowers professionals in the behavioral health and substance recovery sectors with AI-driven assessments, patient intake flows, and compliance tracking. Using an intuitive drag-and-drop interface, counselors can automate evaluations like alcohol/drug use history, trigger recognition, and relapse warning signs. This accelerates onboarding, ensures regulatory alignment, and improves client outcomes through structured conversation flows.',
    category: 'Healthcare Technology',
    filterType: 'SAAS',
    status: 'Live',
    rating: 4.6,
    users: '5K+',
    features: [
      'Dynamic assessment flow builder',
      'Real-time client response capture',
      'Addiction history tracking',
      'Relapse indicator questionnaires',
      'HIPAA-compliant data handling',
      'Support system evaluation',
      'Integrated logic and branching',
      'Exportable reports for therapists',
    ],
    highlights: [
      'Used in 50+ recovery centers',
      'Reduces assessment time by 60%',
      'Improves documentation accuracy',
      'Built-in triggers for red-flag behaviors',
    ],
    demoImages: [
      '/demo/stock mate ai/Screenshot 2025-11-02 014307.png',
      '/demo/stock mate ai/Screenshot 2025-11-02 014323.png',
      '/demo/stock mate ai/Screenshot 2025-11-02 014333.png',
    ],
    demoUrl: 'https://web.telegram.org/k/#@Stockmateai_bot',
    icon: ClipboardList,
    gradient: 'from-rose-500 to-pink-500',
    accentColor: 'text-rose-600',
  },
  {
    id: 15,
    title: 'MyPnL',
    subtitle: 'Personalized Learning & Exam Assistant',
    description:
      'An adaptive AI-powered learning platform that customizes study materials, quizzes, and performance analytics for students and educators.',
    longDescription:
      'EduNex AI transforms education with dynamic course personalization. The system adapts to each learner’s performance, adjusting question difficulty, recommending resources, and generating weekly performance reports. Teachers can monitor classroom analytics, while students get AI-suggested learning paths, flashcards, and timed practice exams tailored to their progress.',
    category: 'Education Technology',
    filterType: 'SAAS',
    status: 'Live',
    rating: 4.8,
    users: '120K+',
    features: [
      'Adaptive quiz generation',
      'Smart progress tracking dashboard',
      'AI-based learning path recommendations',
      'Flashcard and note generator',
      'Exam readiness score visualization',
      'Classroom management for teachers',
      'Student ranking system',
    ],
    highlights: [
      'Improves learning speed by 40%',
      'Used by 300+ schools worldwide',
      '98% teacher satisfaction rate',
      'Multi-language content support',
    ],
    demoImages: [
      '/demo/mypnl/Screenshot 2025-11-02 014433.png',
      '/demo/mypnl/mypnl.pro_settings.png',
      '/demo/mypnl/Screenshot 2025-11-02 014239.png',
      '/demo/mypnl/Screenshot 2025-11-02 014340.png',
      '/demo/mypnl/Screenshot 2025-11-02 014221.png',
      '/demo/mypnl/Screenshot 2025-11-02 014329.png',
    ],
    demoUrl: 'https://mypnl.pro/',
    icon: Star,
    gradient: 'from-indigo-500 to-blue-500',
    accentColor: 'text-indigo-600',
  },
  {
    id: 16,
    title: 'StockInsider.io',
    subtitle: 'Personalized Learning & Exam Assistant',
    description:
      'An adaptive AI-powered learning platform that customizes study materials, quizzes, and performance analytics for students and educators.',
    longDescription:
      'EduNex AI transforms education with dynamic course personalization. The system adapts to each learner’s performance, adjusting question difficulty, recommending resources, and generating weekly performance reports. Teachers can monitor classroom analytics, while students get AI-suggested learning paths, flashcards, and timed practice exams tailored to their progress.',
    category: 'Education Technology',
    filterType: 'SAAS',
    status: 'Live',
    rating: 4.8,
    users: '120K+',
    features: [
      'Adaptive quiz generation',
      'Smart progress tracking dashboard',
      'AI-based learning path recommendations',
      'Flashcard and note generator',
      'Exam readiness score visualization',
      'Classroom management for teachers',
      'Student ranking system',
    ],
    highlights: [
      'Improves learning speed by 40%',
      'Used by 300+ schools worldwide',
      '98% teacher satisfaction rate',
      'Multi-language content support',
    ],
    demoImages: [
      '/demo/stockinsider/Screenshot 2025-11-02 010057.png',
      '/demo/stockinsider/Screenshot 2025-11-02 012157.png',
      '/demo/stockinsider/Screenshot 2025-11-02 012712.png',
      '/demo/stockinsider/Screenshot 2025-11-02 012739.png',
      '/demo/stockinsider/Screenshot 2025-11-02 012836.png',
      '/demo/stockinsider/Screenshot 2025-11-02 012935.png',
      '/demo/stockinsider/Screenshot 2025-11-02 013038.png',
      '/demo/stockinsider/Screenshot 2025-11-02 013100.png',
      '/demo/stockinsider/Screenshot 2025-11-02 013136.png',
    ],
    demoUrl: 'https://www.stockinsider.io/',
    icon: Star,
    gradient: 'from-indigo-500 to-blue-500',
    accentColor: 'text-indigo-600',
  },
  {
    id: 11,
    title: 'Luxor',
    subtitle: 'Personalized Learning & Exam Assistant',
    description:
      'An adaptive AI-powered learning platform that customizes study materials, quizzes, and performance analytics for students and educators.',
    longDescription:
      'EduNex AI transforms education with dynamic course personalization. The system adapts to each learner’s performance, adjusting question difficulty, recommending resources, and generating weekly performance reports. Teachers can monitor classroom analytics, while students get AI-suggested learning paths, flashcards, and timed practice exams tailored to their progress.',
    category: 'Education Technology',
    filterType: 'SAAS',
    status: 'Live',
    rating: 4.8,
    users: '120K+',
    features: [
      'Adaptive quiz generation',
      'Smart progress tracking dashboard',
      'AI-based learning path recommendations',
      'Flashcard and note generator',
      'Exam readiness score visualization',
      'Classroom management for teachers',
      'Student ranking system',
    ],
    highlights: [
      'Improves learning speed by 40%',
      'Used by 300+ schools worldwide',
      '98% teacher satisfaction rate',
      'Multi-language content support',
    ],
    demoImages: [
      '/demo/luxor/Screenshot 2025-10-29 115949.png',
      '/demo/luxor/Screenshot 2025-10-29 115245.png',
      '/demo/luxor/Screenshot 2025-10-29 115255.png',
      '/demo/luxor/Screenshot 2025-10-29 115304.png',
      '/demo/luxor/Screenshot 2025-10-29 115336.png',
    ],
    demoUrl: 'https://luxorapp.vercel.app/',
    icon: Star,
    gradient: 'from-indigo-500 to-blue-500',
    accentColor: 'text-indigo-600',
  },
  {
    id: 12,
    title: 'Smart Desk AI',
    subtitle: 'Smart Office Automation & Productivity Suite',
    description:
      'AI-driven platform that converts long-form content into short viral clips optimized for social media.',
    longDescription:
      'ClipCraft AI analyzes long-form videos to identify highlight moments using speech sentiment, engagement cues, and scene detection. It then auto-generates short clips with subtitles, transitions, and brand overlays for platforms like TikTok, YouTube Shorts, and Instagram Reels. Ideal for creators, agencies, and marketing teams who want to repurpose content effortlessly.',
    category: 'Content Creation',
    filterType: 'AI AGENTS',
    status: 'Beta',
    rating: 4.6,
    users: '45K+',
    features: [
      'Automatic scene detection',
      'AI subtitle generation',
      'Smart background music sync',
      'Brand logo watermarking',
      'Social platform export presets',
      'Batch upload & render queue',
      'Engagement analytics dashboard',
    ],
    highlights: [
      'Saves 12+ hours of manual editing weekly',
      'Auto-detects best 15–60 sec moments',
      'Supports 4K rendering and SRT export',
      'Trusted by 800+ content creators',
    ],
    demoImages: [
      '/demo/smart desk ai/Screenshot 2025-10-29 115510.png',
      '/demo/smart desk ai/Screenshot 2025-10-29 115408.png',
      '/demo/smart desk ai/Screenshot 2025-10-29 115531.png',
      '/demo/smart desk ai/Screenshot 2025-10-29 115615.png',
      '/demo/smart desk ai/Screenshot 2025-10-29 115628.png',
    ],
    demoUrl: 'https://smartdeskai.vercel.app/',
    icon: Camera,
    gradient: 'from-pink-500 to-rose-500',
    accentColor: 'text-pink-600',
  },
  {
    id: 13,
    title: 'IQONA',
    subtitle: 'AI-Powered Talent Management Suite',
    description:
      'AI-based hiring assistant that automates candidate screening, skill tests, and cultural fit evaluation.',
    longDescription:
      'TalentIQ uses AI to optimize the recruitment process. It automatically parses resumes, generates candidate insights, and evaluates skill compatibility. Using behavioral scoring and sentiment analysis from recorded interviews, recruiters can shortlist candidates faster. The dashboard includes analytics, diversity metrics, and hiring pipeline automation.',
    category: 'Human Resources',
    filterType: 'SAAS',
    status: 'Live',
    rating: 4.9,
    users: '80K+',
    features: [
      'Automated resume parsing',
      'AI interview transcription & scoring',
      'Behavioral and skill-based ranking',
      'Diversity & inclusion analytics',
      'ATS (Applicant Tracking System) integration',
      'Recruiter dashboard & candidate notes',
    ],
    highlights: [
      'Reduces hiring time by 60%',
      'Used by 500+ companies globally',
      '98% accuracy in skill-based scoring',
      'GDPR-compliant candidate data handling',
    ],
    demoImages: [
      '/demo/iqona/Screenshot 2025-10-29 114517.png',
      '/demo/iqona/Screenshot 2025-10-29 114534.png',
      '/demo/iqona/Screenshot 2025-10-29 114636.png',
      '/demo/iqona/Screenshot 2025-10-29 114659.png',
      '/demo/iqona/Screenshot 2025-10-29 114720.png',
    ],
    demoUrl: 'https://iqona-mvp.vercel.app/',
    icon: Users,
    gradient: 'from-violet-500 to-fuchsia-500',
    accentColor: 'text-violet-600',
  },
  {
    id: 14,
    title: 'Orkust',
    subtitle: 'AI-Powered Sustainability Suite for Businesses',
    description:
      'Monitors energy consumption, carbon emissions, and sustainability KPIs using smart AI insights for businesses.',
    longDescription:
      'EcoVision helps organizations measure and reduce their environmental footprint. Using IoT data and AI-based predictions, it analyzes electricity, water, and gas usage, forecasts carbon emissions, and provides actionable insights to meet ESG goals. The platform includes sustainability scoring, visualization dashboards, and automated reporting tools.',
    category: 'Sustainability & Analytics',
    filterType: 'SAAS',
    status: 'Live',
    rating: 4.8,
    users: '22K+',
    features: [
      'Carbon emission forecasting',
      'IoT-based data ingestion',
      'Automated ESG report generation',
      'Energy savings recommendations',
      'Interactive sustainability dashboards',
      'Multi-site monitoring',
    ],
    highlights: [
      'Reduces energy waste by 35%',
      'Compatible with 200+ IoT devices',
      'Used by top eco-certified firms',
      'Automates ESG reports in minutes',
    ],
    demoImages: [
      '/demo/orkust/Screenshot 2025-10-29 114417.png',
      '/demo/orkust/Screenshot 2025-10-29 114429.png',
      '/demo/orkust/Screenshot 2025-10-29 114741.png',
      '/demo/orkust/Screenshot 2025-10-29 114805.png',
      '/demo/orkust/Screenshot 2025-10-29 114814.png',
    ],
    demoUrl: 'https://orkust-capital.vercel.app/',
    icon: Leaf,
    gradient: 'from-green-600 to-lime-500',
    accentColor: 'text-green-600',
  },
  {
    id: 1,
    title: 'Travel AI',
    subtitle: 'Smart Travel Planning Assistant',
    description:
      'AI-powered travel planning chatbot that creates personalized itineraries, finds the best accommodations, and provides real-time travel assistance.',
    longDescription:
      'Experience the future of travel planning with Travel AI. Our intelligent chatbot analyzes thousands of destinations, hotels, and attractions to create personalized 3-day itineraries tailored to your preferences. From booking luxury hotels like CITADINES TRAFALGAR SQ LONDON to suggesting the perfect punting experience in Cambridge, Travel AI handles every detail of your journey.',
    category: 'Travel & Tourism',
    filterType: 'AI AGENTS',
    status: 'Live',
    rating: 4.8,
    users: '50K+',
    features: [
      'Personalized 3-day itineraries',
      'Real-time hotel booking',
      'Route optimization with cost analysis',
      'Multi-destination planning',
      'Transportation cost calculator',
      'Interactive maps and navigation',
      '24/7 travel assistance',
      'Local attraction recommendations',
    ],
    highlights: [
      'Plans trips to 200+ destinations',
      'Integrates with 1000+ hotels worldwide',
      '95% customer satisfaction rate',
      'Available in 15 languages',
    ],
    demoImages: [
      '/demo/travel/Travel AI - 1.webp',
      '/demo/travel/Travel AI - 2.webp',
      '/demo/travel/Travel AI - 3.webp',
      '/demo/travel/Travel AI - 4.webp',
      '/demo/travel/Travel AI - 5.webp',
      '/demo/travel/Travel AI - 6.webp',
    ],
    tags: ['Next.js', 'React', 'Tailwind CSS', 'Generative UI Framework'],
    demoUrl: 'https://travel.arklab.online/',
    icon: Globe,
    gradient: 'from-blue-500 to-cyan-500',
    accentColor: 'text-blue-600',
  },
  {
    id: 2,
    title: 'Super Trader AI',
    subtitle: 'Autonomous Crypto Trading Bot',
    description:
      'Advanced AI-powered cryptocurrency arbitrage trading bot that automatically identifies and executes profitable trades across multiple exchanges 24/7.',
    longDescription:
      'Super Trader AI revolutionizes cryptocurrency trading with intelligent arbitrage opportunities detection. Our sophisticated algorithm monitors price differences across major exchanges like Binance, Bybit, MEXC, and more, executing profitable trades automatically. With a 100% success rate in recent trades and comprehensive risk management, Super Trader AI maximizes your crypto profits while you sleep.',
    category: 'Financial Technology',
    filterType: 'SAAS',
    status: 'Live',
    rating: 4.9,
    users: '10K+',
    features: [
      'Automated arbitrage trading',
      'Multi-exchange integration',
      'Real-time market analysis',
      'Risk management system',
      'Profit tracking & analytics',
      'Trade history & reporting',
      'API key management',
      'Customizable trading parameters',
    ],
    highlights: [
      '100% success rate in recent trades',
      'Supports 6+ major exchanges',
      'Average 15% monthly returns',
      '24/7 automated trading',
    ],
    demoImages: [
      '/demo/trade/Super Trader AI - 1.webp',
      '/demo/trade/Super Trader AI - 2.webp',
      '/demo/trade/Super Trader AI - 3.webp',
      '/demo/trade/Super Trader AI - 6.webp',
      '/demo/trade/Super Trader AI - 8.webp',
      '/demo/trade/Super Trader AI - 14.webp',
    ],
    demoUrl: 'https://ui.super-trader.xyz',
    icon: TrendingUp,
    gradient: 'from-green-500 to-emerald-500',
    accentColor: 'text-green-600',
  },
  {
    id: 3,
    title: 'Chatply',
    subtitle: 'AI That Fuels the Growth of Your Work',
    description:
      'AI-powered compliance and business growth assistant that provides 24/7 support, customized guidance, and quick resolution for regulatory requirements.',
    longDescription:
      "Chatply simplifies business regulations and compliance for companies of all sizes. Our AI-powered platform offers round-the-clock access to compliance solutions, tailored guidance for specific industries, and quick resolution of regulatory questions. Whether you're a startup or established business, Chatply helps keep your operations compliant while saving time and resources through unlimited queries and secure data handling.",
    category: 'Business Compliance & Support',
    filterType: 'AI AGENTS',
    status: 'Live',
    rating: 4.7,
    users: '25K+',
    features: [
      '24/7 Access to compliance support',
      'Customized industry-specific guidance',
      'Quick resolution of regulatory questions',
      'Unlimited queries with no restrictions',
      'Secure and private data handling',
      'Regulatory Compliance AI Chatbot',
      'Advanced financial tools',
      'Priority expert support',
      'Seamless software integration',
    ],
    highlights: [
      'Reduces compliance resolution time by 70%',
      'Supports 50+ industry regulations',
      '98% user satisfaction rate',
      'Available in multiple languages',
    ],
    demoImages: [
      '/demo/chatply/CHATPLY1.png',
      '/demo/chatply/CHATPLYPRIM.png',
      '/demo/chatply/CHATPLY2.png',
      '/demo/chatply/CHATPLY3.png',
    ],
    demoUrl: 'https://www.nobles.com/contact?id=1.3',
    icon: ShieldCheck,
    gradient: 'from-purple-500 to-indigo-500',
    accentColor: 'text-purple-600',
    contact: {
      email: 'contact@nobles.com',
      website: 'https://www.nobles.com',
      supportLink: 'https://www.nobles.com/contact?id=1.3',
    },
    purpose: [
      'Digital marketing platform integration',
      'Digital content creation monitoring',
      'Product delivery optimization',
      'Brand-friendly platform maintenance',
    ],
  },
  {
    id: 4,
    title: 'Acetdui AI',
    subtitle: 'AI for Behavioral Health & Compliance Screening',
    description:
      'Streamlined AI solution for behavioral health assessments, compliance evaluations, and recovery support workflows.',
    longDescription:
      'Acetdui empowers professionals in the behavioral health and substance recovery sectors with AI-driven assessments, patient intake flows, and compliance tracking. Using an intuitive drag-and-drop interface, counselors can automate evaluations like alcohol/drug use history, trigger recognition, and relapse warning signs. This accelerates onboarding, ensures regulatory alignment, and improves client outcomes through structured conversation flows.',
    category: 'Healthcare Technology',
    filterType: 'SAAS',
    status: 'Live',
    rating: 4.6,
    users: '5K+',
    features: [
      'Dynamic assessment flow builder',
      'Real-time client response capture',
      'Addiction history tracking',
      'Relapse indicator questionnaires',
      'HIPAA-compliant data handling',
      'Support system evaluation',
      'Integrated logic and branching',
      'Exportable reports for therapists',
    ],
    highlights: [
      'Used in 50+ recovery centers',
      'Reduces assessment time by 60%',
      'Improves documentation accuracy',
      'Built-in triggers for red-flag behaviors',
    ],
    demoImages: [
      '/demo/acetdui/Screenshot 2025-07-18 at 16-52-24 informal hearing Make.png',
      '/demo/acetdui/Screenshot 2025-07-18 at 16-52-52 intake into counseling Make.png',
      '/demo/acetdui/Screenshot 2025-07-18 at 16-55-21 Scenarios Make.png',
      '/demo/acetdui/Screenshot 2025-07-18 at 17-27-14 Acetdui Services.png',
      '/demo/acetdui/Screenshot 2025-07-18 at 17-27-48 Acetdui Services.png',
      '/demo/acetdui/Screenshot 2025-07-18 at 17-28-09 Acetdui Services.png',
      '/demo/acetdui/Screenshot 2025-07-18 at 17-28-21 Acetdui Services.png',
    ],
    demoUrl: 'https://acetdui.app',
    icon: ClipboardList,
    gradient: 'from-rose-500 to-pink-500',
    accentColor: 'text-rose-600',
  },
  {
    id: 5,
    title: 'Bio Naturee (SaaS)',
    subtitle: 'Organic Commerce & AI Automation Platform',
    description:
      'A complete SaaS platform that empowers organic brands with a ready-to-launch storefront and intelligent AI-powered automation.',
    longDescription:
      'Bionaturee is a modern SaaS solution built for organic product sellers. It offers a fully responsive and visually appealing e-commerce storefront, complete with category browsing, cart functionality, and clean design. On the backend, it integrates with a powerful Voiceflow-based AI automation builder that enables customer support flows, product recommendations, live call scheduling, and more — all without writing code. Ideal for eco-brands aiming to scale sustainably.',
    category: 'SaaS | E-commerce + Automation',
    filterType: 'SAAS',
    status: 'Live',
    rating: 4.7,
    users: '35K+',
    features: [
      'Pre-built organic e-commerce storefront',
      'Juice, groceries, veggies & more categories',
      'AI chatbot builder (Voiceflow-powered)',
      'Live product recommendations & FAQs',
      'Responsive design optimized for conversions',
      'Integrated checkout and pricing logic',
      'Drag-and-drop automation for customer support',
      'Call scheduling, inquiry resolution, and flows',
    ],
    highlights: [
      'No-code chatbot automation builder',
      'Ideal for eco-conscious brands and sellers',
      'Reduces support time by up to 70%',
      'Boosts customer satisfaction and engagement',
      'Beautiful UI with real-time cart and pricing',
    ],
    demoImages: [
      '/demo/bio naturee/Screenshot-from-2024-06-17-13-35-25.png.webp',
      '/demo/bio naturee/bionaturee- automations.png',
    ],
    demoUrl: 'https://bionaturee.shop',
    icon: Leaf,
    gradient: 'from-green-500 to-emerald-500',
    accentColor: 'text-green-600',
  },
  {
    id: 6,
    title: 'iboothme',
    subtitle: 'Web-Based AR Photobooth & Engagement Platform',
    description:
      'Interactive web-based AR photo experience with branded filters, scavenger hunts, and prize wheels - no app download required.',
    longDescription:
      'Virtual Photo Booth Pro revolutionizes event engagement with a complete web-based solution featuring AR photo filters, scavenger hunts with QR code integration, and spin-to-win prize wheels. Brands like IBM, Guinness, and Pepsi trust our platform to create memorable experiences that work on any device without additional apps. The white-label solution includes storage integration, ready-made templates, and customizable engagement campaigns.',
    category: 'Event Technology & Engagement',
    filterType: 'AI AGENTS',
    status: 'Live',
    rating: 4.8,
    users: '75K+',
    features: [
      'Web-based AR photo filters (no app needed)',
      'QR code scavenger hunt integration',
      'Spin-the-wheel prize mechanics',
      'White-label branding options',
      'Dropbox/Google Drive/S3 storage integration',
      'Ready-made experience templates (iStore)',
      'Cross-device compatibility (mobile/desktop)',
      'Customizable event duration (1 day to 1 year)',
      'Email campaign integration',
      'Dashboard analytics',
    ],
    highlights: [
      'Trusted by Fortune 500 brands',
      '90% participant engagement rate',
      'Reduces event setup time by 80%',
      'No-code experience builder',
      'Works on any smartphone or device',
    ],
    demoImages: [
      '/demo/iboothme/Screenshot 2025-07-18 at 16-36-39 Free Online Virtual Photo Booth App Spin the Wheel Prize Ideas- (1).png',
      '/demo/iboothme/Screenshot 2025-07-18 at 16-36-39 Free Online Virtual Photo Booth App Spin the Wheel Prize Ideas- (2).png',
      '/demo/iboothme/Screenshot 2025-07-18 at 16-36-39 Free Online Virtual Photo Booth App Spin the Wheel Prize Ideas- (3).png',
      '/demo/iboothme/Screenshot 2025-07-18 at 16-36-39 Free Online Virtual Photo Booth App Spin the Wheel Prize Ideas- (4).png',
      '/demo/iboothme/Screenshot 2025-07-18 at 16-36-39 Free Online Virtual Photo Booth App Spin the Wheel Prize Ideas- (5).png',
    ],
    demoUrl: 'https://photobooth.engagepro.com',
    icon: Camera,
    gradient: 'from-fuchsia-500 to-purple-500',
    accentColor: 'text-fuchsia-600',
  },
  {
    id: 7,
    title: 'BritiTrade AI',
    subtitle: 'One-Click Trading Action Panel',
    description:
      'Streamlined interface for quick trading actions and execution with integrated sharing capabilities.',
    longDescription:
      'BritiTrade AI provides traders with instant access to essential functions through a minimalist action panel. The interface enables one-click execution of key trading operations including sharing trade setups, contacting support, running trading algorithms, and publishing market analysis - all optimized for speed and efficiency in fast-moving markets.',
    category: 'Trading Technology',
    filterType: 'SAAS',
    status: 'Live',
    rating: 4.7,
    users: '15K+',
    features: [
      'One-click action execution',
      'Trade setup sharing functionality',
      'Direct support call access',
      'Algorithm execution button',
      'Analysis publishing portal',
      'Minimalist trader-focused UI',
      'Low-latency order routing',
    ],
    highlights: [
      'Execute actions 70% faster than traditional platforms',
      'Trusted by 15,000+ active traders',
      'Integrated with major broker APIs',
      'All actions complete in <300ms',
    ],

    demoImages: [
      '/demo/brititrade/Screenshot 2025-07-18 at 17-15-31 BritiTrade AI(1).png',
    ],
    demoVideos: [
      '/demo/brititrade/Screen Recording 2025-07-18 at 5.15.59 PM(1).mov',
    ],
    demoUrl: 'https://trade.briti-ai.com/panel',
    icon: Zap,
    gradient: 'from-amber-500 to-orange-500',
    accentColor: 'text-amber-600',
  },
  {
    id: 8,
    title: 'Doc On Time',
    subtitle: 'AI-Powered Medical Booking & Triage Assistant',
    description:
      'Conversational bot to help users book appointments, diagnose symptoms, or inquire about doctors.',
    longDescription:
      'This AI-driven chatbot assists patients in navigating healthcare services by offering appointment bookings, superficial disease diagnosis, and doctor information. It guides the user through a flow-based conversation, collecting necessary details like name, email, and symptoms. The logic uses conditional branching and simple classification to direct the user to the right flow.',
    category: 'Healthcare AI Assistant',
    filterType: 'AI AGENTS',
    status: 'Prototype',
    rating: 4.6,
    users: '5K+',
    features: [
      'Appointment booking flow',
      'Basic symptom-to-condition diagnosis',
      'Doctor information flow',
      'Conditional logic branching',
      'User input capture (name, email, time)',
      'Label-based logic handling (intent classification)',
      'No-code drag-and-drop builder interface',
      'Integrated reply storage for CRM sync',
    ],
    highlights: [
      'Streamlined patient onboarding',
      'Collects structured data for clinics',
      'Easily modifiable for any medical use case',
      'Quick to deploy with minimal setup',
      'Natural conversation design',
    ],
    demoImages: [
      '/demo/doc on time/Screenshot 2025-07-18 at 17-11-01 Doctor Appointment by Arklab AI.png',
    ],
    demoVideos: [
      '/demo/doc on time/Screen Recording 2025-07-18 at 5.11.51 PM.mov',
    ],
    demoUrl: 'https://arklab.ai/doctor-bot-demo',
    icon: Stethoscope,
    gradient: 'from-green-400 to-teal-500',
    accentColor: 'text-green-600',
  },
  {
    id: 9,
    title: 'Ilynk App',
    subtitle: 'Service & Product Marketplace for Creators',
    description:
      'A visually rich marketplace where users can browse, book, or buy digital services and products directly from creators.',
    longDescription:
      'The Creator Marketplace is a mobile-first platform for exploring, filtering, and purchasing creative services or digital products. Users can browse by category, search, or use filters such as newest or verified sellers. Integrated navigation and beautiful card layouts enhance the buyer experience. Tabs and visual elements make the app intuitive and quick to explore.',
    category: 'Marketplace Platform',
    filterType: 'MOBILE APP',
    status: 'Live',
    rating: 4.9,
    users: '50K+',
    features: [
      'Product & service toggle (All / Services / Products)',
      'Search & category filtering',
      'Verified seller indicator',
      'Favorites (heart icon)',
      'Category-based browsing tiles',
      'Sorting (e.g., Newest First)',
      'Bottom navigation tabs (Home, Market, Orders, Profile)',
      'Modern dark theme UI with gradients',
    ],
    highlights: [
      'Mobile-first UX with swipe-friendly layout',
      'Filter by services/products instantly',
      'Custom seller verification system',
      'Great for freelancers, creators, and niche sellers',
      'Polished category browsing system',
    ],
    demoImages: [
      '/demo/ilynk/photo_2025-07-18 16.39.05-min.jpeg',
      '/demo/ilynk/photo_2025-07-18 16.39.08-min.jpeg',
      '/demo/ilynk/photo_2025-07-18 16.39.11-min.jpeg',
      '/demo/ilynk/photo_2025-07-18 16.39.14-min.jpeg',
      '/demo/ilynk/photo_2025-07-18 16.39.16-min.jpeg',
      '/demo/ilynk/photo_2025-07-18 16.39.19-min.jpeg',
      '/demo/ilynk/photo_2025-07-18 16.39.22-min.jpeg',
      '/demo/ilynk/photo_2025-07-18 16.39.25-min.jpeg',
      '/demo/ilynk/photo_2025-07-18 16.39.27-min.jpeg',
      '/demo/ilynk/photo_2025-07-18 16.39.29-min.jpeg',
      '/demo/ilynk/photo_2025-07-18 16.39.32-min.jpeg',
      '/demo/ilynk/photo_2025-07-18 16.39.37-min.jpeg',
    ],
    demoUrl: 'https://creator.marketplace.app/demo',
    icon: Store,
    gradient: 'from-blue-400 to-violet-500',
    accentColor: 'text-blue-600',
  },
  {
    id: 10,
    title: 'IAMSKIN US',
    subtitle: 'Korean & Japanese Skincare Marketplace',
    description:
      'Premium Asian beauty products shipped directly from Korea with free shipping options and step-by-step skincare routines.',
    longDescription:
      'Iamskin specializes in authentic Korean and Japanese skincare products, offering everything from cult-favorite brands like COSRX and BEAUTY OF JOSEON to complete skincare routines. The platform features free international shipping thresholds, real-time inventory tracking, and expert-curated product bundles for all skin types and concerns. With 114+ lip care products alone and bestselling items like the Ground Rice and Honey Glow Mask, Iamskin brings K-beauty innovation to global customers.',
    category: 'E-commerce | Beauty & Skincare',
    filterType: 'AI AGENTS',
    status: 'Live',
    rating: 4.9,
    users: '200K+',
    features: [
      'Direct shipping from Korea',
      'Free shipping on orders >$99',
      'Step-by-step skincare routines (8-step system)',
      'Real-time product demand indicators',
      'Wishlist & comparison tools',
      'Expert consultation available',
      'Gift sets & trial kits',
      'Localized currency (BDT)',
      'Inventory status indicators',
      'Cookie consent management',
    ],
    highlights: [
      '200+ authentic Asian beauty brands',
      '30 products sold every 18 hours (average)',
      '15% gift discounts available',
      '#1 global seller for K-beauty',
      'Trending in US markets',
    ],

    demoImages: [
      '/demo/iamskin/Screenshot 2025-07-18 at 15-09-17 Korean & Japanese Skincare Products & Beauty Tools Iamskin (1).png',
      '/demo/iamskin/Screenshot 2025-07-18 at 15-09-17 Korean & Japanese Skincare Products & Beauty Tools Iamskin (2).png',
      '/demo/iamskin/Screenshot 2025-07-18 at 15-09-17 Korean & Japanese Skincare Products & Beauty Tools Iamskin .png',
      '/demo/iamskin/Screenshot 2025-07-18 at 15-09-17 Korean & Japanese Skincare Products & Beauty Tools Iamskin.png',
    ],
    demoUrl: 'https://www.iamskin.com',
    icon: Smile,
    gradient: 'from-rose-400 to-pink-500',
    accentColor: 'text-rose-600',
  },
];
